const {
  REACT_APP_SENTRY_DSN,
  REACT_APP_APP_NAME,
  REACT_APP_APP_VERSION,
  REACT_APP_CLIENT_ID,
  REACT_APP_BASE_URL,
} = process.env;

const GRAPHQL_ENDPOINT = `${REACT_APP_BASE_URL}/graphql`;
const V1_ENDPOINT = `${REACT_APP_BASE_URL}/v1`;

export default {
  APP_NAME: REACT_APP_APP_NAME,
  APP_VERSION: REACT_APP_APP_VERSION,
  SENTRY_DSN: REACT_APP_SENTRY_DSN,
  CLIENT_ID: REACT_APP_CLIENT_ID,
  GRAPHQL_ENDPOINT,
  V1_ENDPOINT,
};
